// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFtUhLM_tH0-ed4dg2C-zn7zu7GMdVFk',
    appId: '1:255648610268:web:88282edadc320fbb71c119',
    messagingSenderId: '255648610268',
    projectId: 'test2-cf263',
    authDomain: 'test2-cf263.firebaseapp.com',
    storageBucket: 'test2-cf263.firebasestorage.app',
    measurementId: 'G-ZZJ5JKT1WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_ohMne7h4yz19NNPjTQSZAT3djBkxqc',
    appId: '1:255648610268:android:3a5366866d4c1e7e71c119',
    messagingSenderId: '255648610268',
    projectId: 'test2-cf263',
    storageBucket: 'test2-cf263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSAZFI0Bbkuy0QeEbC5aNrYwmTm1Wr-dI',
    appId: '1:255648610268:ios:e19906ece6cb4fd171c119',
    messagingSenderId: '255648610268',
    projectId: 'test2-cf263',
    storageBucket: 'test2-cf263.firebasestorage.app',
    iosBundleId: 'com.example.new2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSAZFI0Bbkuy0QeEbC5aNrYwmTm1Wr-dI',
    appId: '1:255648610268:ios:e19906ece6cb4fd171c119',
    messagingSenderId: '255648610268',
    projectId: 'test2-cf263',
    storageBucket: 'test2-cf263.firebasestorage.app',
    iosBundleId: 'com.example.new2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcFtUhLM_tH0-ed4dg2C-zn7zu7GMdVFk',
    appId: '1:255648610268:web:39461f7bda74401171c119',
    messagingSenderId: '255648610268',
    projectId: 'test2-cf263',
    authDomain: 'test2-cf263.firebaseapp.com',
    storageBucket: 'test2-cf263.firebasestorage.app',
    measurementId: 'G-HMW7EXFVB9',
  );
}
